//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIST
    {
        public int DID { get; set; }
        public string DNAME { get; set; }
        public int SID { get; set; }
    
        public virtual STATE STATE { get; set; }
    }
}
